version: 2
jobs:
  build:
    docker:
      - image: alpine/git
    steps:
      - checkout
      - run:
          name: Dependency
          command: git --version
      - run:
          name: Test
          command: ./test-all.sh
