version: 2
jobs:
  build:
    docker:
      - image: alpine/git
    steps:
      - checkout
      - run:
          name: Dependency
          command: git --version
      - run:
          name: Config
          command: git config --global user.name=Kuniwak && git config --global user.email=orga.chem.job@gmail.com
      - run:
          name: Test
          command: ./test-all.sh
